[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.22"

[features]
seeds = false
skip-lint = false

[programs.devnet]
solve = "Hvk9udYr7cFfsXN2yTKb94A5pLM7H9YvAQtnV5JQfwvz"

[programs.localnet]
solve = "Hvk9udYr7cFfsXN2yTKb94A5pLM7H9YvAQtnV5JQfwvz"

[programs.mainnet]
solve = "Hvk9udYr7cFfsXN2yTKb94A5pLM7H9YvAQtnV5JQfwvz"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/03_init_dex_fee_tier.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metaplex_token_metadata_program.so"

[deploy]
max_compute_units = 200000
priority_fee = 500